name = "demo-router"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# R2 bucket for demo assets
[[r2_buckets]]
binding = "DEMO_ASSETS"
bucket_name = "rozich-demos"

# KV namespace for demo metadata
[[kv_namespaces]]
binding = "DEMO_CONFIG"
id = "b0cc56f8dbf54ebd86d4d43567e1ad99"