name = "demo-router"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# R2 bucket for demo assets
[[r2_buckets]]
binding = "DEMO_ASSETS"
bucket_name = "demo-assets" # Change to your bucket name

# KV namespace for demo metadata
[[kv_namespaces]]
binding = "DEMO_CONFIG"
id = "YOUR_KV_NAMESPACE_ID" # Run setup script or replace with your KV namespace ID

# Optional: Analytics
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"