name = "demo-router"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Custom domain routing
[[routes]]
pattern = "demo.rozich.net/*"
zone_name = "rozich.net"

# R2 bucket for demo assets
[[r2_buckets]]
binding = "DEMO_ASSETS"
bucket_name = "rozich-demos"

# KV namespace for demo metadata
[[kv_namespaces]]
binding = "DEMO_CONFIG"
id = "YOUR_KV_NAMESPACE_ID" # Create in dashboard first

# Optional: Analytics
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"