plugins:
  - "@typescript-eslint"
extends: plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  "@typescript-eslint/explicit-function-return-type": warn
  "@typescript-eslint/no-explicit-any": warn
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"
  no-console: warn
  prefer-const: error
overrides:
  - files:
      - "test/**/*.ts"
      - "vitest.config.ts"
    rules:
      "@typescript-eslint/explicit-function-return-type": "off"
